### ISSUE TITLE
Request for specific syntax highlighting

### ISSUE THREAD

**Issue by hklsb** [xshrim/vscode-txt-syntax#14]
First of all Thank you so much for your extension.
I have been looking for this for a long time as I don't know how to make it.
But then I have one more option I want to have but I couldn't implement  by myself.
I want to color the whole line if it starts with a character "$" like a command
e.g `$ ipconfig /all`
can you help me with that?
Or will it be too complex?
Thank you in advance

**Comment by xshrim** [comment]
It is supported in v0.1.7 with foreground highlight, but background highlight is not supported out of the box.
Maybe you could using the [Highlight extension](https://github.com/fabiospampinato/vscode-highlight) and a regular expression to do this. By example:
https://stackoverflow.com/questions/50341018/vscode-language-specific-background-color-like-notepad
