### ISSUE TITLE
Folding doesn't work

### ISSUE THREAD

**Issue by martinrhan** [xshrim/vscode-txt-syntax#21]
Steps to produce:
1. Add "editor.foldingStrategy": "auto" to setting.json
2. Create any txt file.
3. Type
```
1.
Any text

2.
Any text

3.
Any text
```
4. No folding available

**Comment by xshrim** [comment]
A space is required after the period to be treated as title. Like this:
```
1. AAA
Any text

2. 
Any text

3. BBB
Any text
```
