### ISSUE TITLE
highlight words 的侧边栏在新版vscode上消失了

### ISSUE THREAD

**Issue by go4supper** [xshrim/vscode-txt-syntax#22]
highlight words 的侧边栏在新版vscode上消失了

**Comment by xshrim** [comment]
settings.json添加`  "txtsyntax.showHighlightSidebar": true`, 重启vscode即可.

**Comment by go4supper** [comment]
添加 setting 没有解决,
但是使用 [rsbondi/highlight-words](https://github.com/rsbondi/highlight-words), sidebar可以正常出现.
