### ISSUE TITLE
Add setting

### ISSUE THREAD

**Issue by LatenPath** [xshrim/vscode-txt-syntax#23]
Excuse me, how can I remove them:
![image](https://github.com/xshrim/vscode-txt-syntax/assets/145383056/c6a8a407-8409-4760-9b00-afe33229d8d9)

I can't find any setting affect that.

**Comment by xshrim** [comment]
supported in version v.02.4.

you can disable these menus with the setting below:
```json
"txtsyntax.enableSearchMenu": false,
"txtsyntax.enableHighlightMenu": false,
"txtsyntax.enableFileMenu": false
```
