### ISSUE TITLE
TAB and } bracket problem

### ISSUE THREAD

**Issue by mtloper** [xshrim/vscode-txt-syntax#24]
Hi 
First, nice module and useful
I have problem with this } bracket and tabulation after
Same thing with ) bracket
![bracket](https://github.com/xshrim/vscode-txt-syntax/assets/4001268/8e7ebbb4-9b00-4cc3-9d24-e3c83907a4b6)

**Comment by xshrim** [comment]
this problem shoud not be caused by vscode-txt-syntax extension.
