### ISSUE TITLE
txt syntax安装后选中出现下划线，怎么关闭

### ISSUE THREAD

**Issue by jkxbest** [xshrim/vscode-txt-syntax#25]
如题，图如下：
![Clip_2024-07-05_10-24-40](https://github.com/xshrim/vscode-txt-syntax/assets/38863227/a9fd1e7e-5ee8-478f-bce1-4cb67eeab79c)

**Comment by xshrim** [comment]
settings.json添加`"txtsyntax.enableHighlightLine": false`, 重启vscode即可.

**Comment by xshrim** [comment]
settings.json添加"txtsyntax.enableHighlightLine": false, 重启vscode即可.
