### ISSUE TITLE
Highlight broken due to special characters

### ISSUE THREAD

**Issue by ChefkeGremmen** [xshrim/vscode-txt-syntax#6]
First of all, thanks for this plug-in, finally a way of highlighting EDS files!
Then the issue I encountered, see the screenshot below;
![image](https://user-images.githubusercontent.com/19855805/106712607-7b9bc400-65f9-11eb-9beb-dc5c016d76bc.png)
Somehow the characters '16â€“bit' break the highlighting.

**Comment by xshrim** [comment]
It is not bug. **“** is chinese double quotation marks and double quotation marks support cross-line highlighting.
